### ISSUE TITLE
Variable for PHP version

### ISSUE THREAD

**Issue by davidosomething** [capistrano/composer#10]
I'm hosted on webfactional and the PHP default version is 5.2

5.4 is installed as `php54`
http://blog.webfaction.com/2012/02/a-look-at-our-php-setup/

Any way to add a flag so the script doesn't use the php reported by /usr/bin/env ?

**Comment by tom10271** [comment]
This is not working 

```ruby
SSHKit.config.command_map[:php] = '/usr/bin/php7.3'
```

This is working

```ruby
SSHKit.config.command_map[:bash] = "/bin/bash"
SSHKit.config.command_map[:composer] = "/usr/bin/php7.3 /usr/local/bin/composer"
```
