### ISSUE TITLE
Fetch :deploy_to from stage file

### ISSUE THREAD

**Issue by feedmeastraycat** [capistrano/composer#22]
In my deploy.rb I have `set :deploy_to, '/var/www/my_app'` but in my production.rb I have to have `set :deploy_to, '/home/http/my_app/deploy'`. Composer is downloaded and installed into `/home/http/my_app/deploy/shared/` but when Capistrano tries to run it to install the vendor dir it fails because it looks for `/var/www/my_app`.

The only way to get around this is to move the correct `set :deploy_to` directly in the deploy.rb file. But now I have to change it manually each time I deploy to staging or dev.

Not sure if I have done something wrong though. :) I'm still quite new to Capistrano and my only Ruby knowledge is from Capistrano. 

These are my composer settings in deploy.rb:

``` ruby
set :composer_install_flags, "--no-dev --no-interaction --optimize-autoloader --prefer-dist"
set :composer_roles, :all
set :composer_dump_autoload_flags, '--optimize'
set :composer_download_url, "https://getcomposer.org/installer"

SSHKit.config.command_map[:composer] = "#{shared_path.join("composer.phar")}"
```

**Comment by fxgear-dsc** [comment]
Thanks feedmeastraycat for your solution. I had the same problem and got it working thanks to yours which is the best so far (at least for me :))

**Comment by davidlonjon** [comment]
anks feedmeastraycat for your solution. I had the same problem and got it working thanks to yours which is the best so far (at least for me :))

**Comment by gagarine** [comment]
The "task solution" is kind of ugly. And if you have more than one executable it's not very user friendly.

**Comment by webdevilopers** [comment]
:+1: for a constant solution @gagarine @davidlonjon ! Please also see issue https://github.com/capistrano/composer/issues/43.

**Comment by webdevilopers** [comment]
Any news on this?
