### ISSUE TITLE
Default :composer_working_dir broken

### ISSUE THREAD

**Issue by oliviertassinari** [capistrano/composer#36]

**Comment by swalkinshaw** [comment]
Closing since there's no content.

**Comment by Clindbergh** [comment]
Running 
```bash
cap production deploy
```
works fine. However if I try to run composer separately (via `cap production composer:install`), it fails.

This seems to be due to `:composer_working_dir`, since it's evaluated to be empty within this context.
```bash
DEBUG [c8520f3a] Running /usr/bin/env if test ! -d; then echo "Directory does not exist ''" 1>&2; false; fi as deployer@127.0.0.1
DEBUG [c8520f3a] Command: if test ! -d; then echo "Directory does not exist ''" 1>&2; false; fi
DEBUG [c8520f3a] Finished in 0.552 seconds with exit status 0 (successful).
INFO [7f562ed7] Running /usr/bin/env composer install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader as deployer@127.0.0.1
DEBUG [7f562ed7] Command: cd  && ( SYMFONY_ENV=prod /usr/bin/env composer install --no-dev --prefer-dist --no-interaction --quiet --optimize-autoloader )
                           ^^^
```

**Comment by oliviertassinari** [comment]
I have the same error if I comment this line in my cap file

set :composer_working_dir, -> { fetch(:release_path) }

**Comment by Clindbergh** [comment]
This is actually the default in version >=0.0.5 as of https://github.com/capistrano/composer/commit/1d898fd445dc860be8b7bee676204785d6af5575.

**Comment by Prometee** [comment]
This bug appear with capistrano >= 3.5, please reopen this issue or merge the pull request #47
