### ISSUE TITLE
Shared path is wrong if your deploy_to is different

### ISSUE THREAD

**Issue by gagarine** [capistrano/composer#39]
See https://github.com/capistrano/composer/issues/22

This will not works.
SSHKit.config.command_map[:composer] = "php #{shared_path.join("composer.phar")}"

**Comment by austinpray** [comment]
PRs accepted

**Comment by swalkinshaw** [comment]
This is not an issue with this specific extension. It's just a limitation of Capistrano itself. I suggest you either go with the workaround from #22 or try and bring this issue up on Capistrano.

**Comment by gido** [comment]
I think that in [capistrano-rails](https://github.com/capistrano/rails/blob/master/lib/capistrano/tasks/set_rails_env.rake) they're addressing the same issue.

Maybe something like this do the job:
```ruby
namespace :composer do
  task :set_composer_command_map do
    SSHKit.config.command_map[:composer] = "#{shared_path.join("composer.phar")}"
  end
end

Capistrano::DSL.stages.each do |stage|
  after stage, 'composer:set_composer_command_map'
end
```
