### ISSUE TITLE
fetch(:release_path) for composer_working_dir not set

### ISSUE THREAD

**Issue by timkelty** [capistrano/composer#52]
`composer install` command fails, as `fetch(:release_path)` seems to not yet be set.

Why?

The only thing that works for me is `set :composer_working_dir, current_path`, as `current_path` seems to be set.

Note: `set :composer_working_dir, release_path` also works, only because `release_path` [falls back to using current_path](https://github.com/capistrano/capistrano/blob/master/lib/capistrano/dsl/paths.rb#L21-L23)

**Comment by timkelty** [comment]
Closing until further testing with better example.

**Comment by Prometee** [comment]
current_path == ".../current" and not releases/XXX when the task composer:run is running with capistrano  >= 3.5
